import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Me Cabs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-body bg-white dark:bg-gray-500 text-black dark:text-white">
        {children}
      </body>
    </html>
  );
}
